name: Information System Quality Gate

on:
  push:
    branches:
      - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install
      run: npm install --prefix ./information-system
    - name: Quality Gate
      run: npm run test:quality --prefix ./information-system
